/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.GetOauth2Token200Response;
import org.openapitools.client.model.GetOauth2TokenRevoke200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Oauth2Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public Oauth2Api() {
        this(Configuration.getDefaultApiClient());
    }

    public Oauth2Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getOauth2Token
     * @param grantType  (required)
     * @param code Required if grant_type &#x3D; &#x60;authorization_code&#x60;. (optional)
     * @param refreshToken Required if grant_type &#x3D; &#x60;refresh_token&#x60;. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOauth2TokenCall(String grantType, String code, String refreshToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/oauth2/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (grantType != null) {
            localVarFormParams.put("grant_type", grantType);
        }

        if (code != null) {
            localVarFormParams.put("code", code);
        }

        if (refreshToken != null) {
            localVarFormParams.put("refresh_token", refreshToken);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOauth2TokenValidateBeforeCall(String grantType, String code, String refreshToken, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'grantType' is set
        if (grantType == null) {
            throw new ApiException("Missing the required parameter 'grantType' when calling getOauth2Token(Async)");
        }

        return getOauth2TokenCall(grantType, code, refreshToken, _callback);

    }

    /**
     * Request an access token using an existing grant
     * Supported grant types: &#x60;authorization_code&#x60;, and &#x60;refresh_token&#x60;.  Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param grantType  (required)
     * @param code Required if grant_type &#x3D; &#x60;authorization_code&#x60;. (optional)
     * @param refreshToken Required if grant_type &#x3D; &#x60;refresh_token&#x60;. (optional)
     * @return GetOauth2Token200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GetOauth2Token200Response getOauth2Token(String grantType, String code, String refreshToken) throws ApiException {
        ApiResponse<GetOauth2Token200Response> localVarResp = getOauth2TokenWithHttpInfo(grantType, code, refreshToken);
        return localVarResp.getData();
    }

    /**
     * Request an access token using an existing grant
     * Supported grant types: &#x60;authorization_code&#x60;, and &#x60;refresh_token&#x60;.  Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param grantType  (required)
     * @param code Required if grant_type &#x3D; &#x60;authorization_code&#x60;. (optional)
     * @param refreshToken Required if grant_type &#x3D; &#x60;refresh_token&#x60;. (optional)
     * @return ApiResponse&lt;GetOauth2Token200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetOauth2Token200Response> getOauth2TokenWithHttpInfo(String grantType, String code, String refreshToken) throws ApiException {
        okhttp3.Call localVarCall = getOauth2TokenValidateBeforeCall(grantType, code, refreshToken, null);
        Type localVarReturnType = new TypeToken<GetOauth2Token200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Request an access token using an existing grant (asynchronously)
     * Supported grant types: &#x60;authorization_code&#x60;, and &#x60;refresh_token&#x60;.  Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param grantType  (required)
     * @param code Required if grant_type &#x3D; &#x60;authorization_code&#x60;. (optional)
     * @param refreshToken Required if grant_type &#x3D; &#x60;refresh_token&#x60;. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOauth2TokenAsync(String grantType, String code, String refreshToken, final ApiCallback<GetOauth2Token200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOauth2TokenValidateBeforeCall(grantType, code, refreshToken, _callback);
        Type localVarReturnType = new TypeToken<GetOauth2Token200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getOauth2TokenRevoke
     * @param authorization OAuth2 client credentials in the Basic authorization format. (required)
     * @param token  (required)
     * @param tokenHint  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOauth2TokenRevokeCall(String authorization, String token, String tokenHint, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/oauth2/token/revoke";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarFormParams.put("token", token);
        }

        if (tokenHint != null) {
            localVarFormParams.put("token_hint", tokenHint);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOauth2TokenRevokeValidateBeforeCall(String authorization, String token, String tokenHint, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling getOauth2TokenRevoke(Async)");
        }

        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getOauth2TokenRevoke(Async)");
        }

        return getOauth2TokenRevokeCall(authorization, token, tokenHint, _callback);

    }

    /**
     * Revoke an existing access or refresh token
     * Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param authorization OAuth2 client credentials in the Basic authorization format. (required)
     * @param token  (required)
     * @param tokenHint  (optional)
     * @return GetOauth2TokenRevoke200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GetOauth2TokenRevoke200Response getOauth2TokenRevoke(String authorization, String token, String tokenHint) throws ApiException {
        ApiResponse<GetOauth2TokenRevoke200Response> localVarResp = getOauth2TokenRevokeWithHttpInfo(authorization, token, tokenHint);
        return localVarResp.getData();
    }

    /**
     * Revoke an existing access or refresh token
     * Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param authorization OAuth2 client credentials in the Basic authorization format. (required)
     * @param token  (required)
     * @param tokenHint  (optional)
     * @return ApiResponse&lt;GetOauth2TokenRevoke200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetOauth2TokenRevoke200Response> getOauth2TokenRevokeWithHttpInfo(String authorization, String token, String tokenHint) throws ApiException {
        okhttp3.Call localVarCall = getOauth2TokenRevokeValidateBeforeCall(authorization, token, tokenHint, null);
        Type localVarReturnType = new TypeToken<GetOauth2TokenRevoke200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Revoke an existing access or refresh token (asynchronously)
     * Must authenticate via HTTP Basic Authentication, using your OAuth2 client credentials.
     * @param authorization OAuth2 client credentials in the Basic authorization format. (required)
     * @param token  (required)
     * @param tokenHint  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOauth2TokenRevokeAsync(String authorization, String token, String tokenHint, final ApiCallback<GetOauth2TokenRevoke200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOauth2TokenRevokeValidateBeforeCall(authorization, token, tokenHint, _callback);
        Type localVarReturnType = new TypeToken<GetOauth2TokenRevoke200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
