/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import org.openapitools.client.model.GetResourcesDiscoverCategories200Response;
import org.openapitools.client.model.GetResourcesDiscoverResources200Response;
import org.openapitools.client.model.GetResourcesDiscoverResources4XXResponse;
import org.openapitools.client.model.GetV2ResourcesDiscoverCartView200Response;
import org.openapitools.client.model.GetV2ResourcesDiscoverLicenses200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartAdd2XXResponse;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartAddRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCheckout200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponAdd200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponAddRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponRemove200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponRemoveRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartRemove200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartRemoveRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ResourcesDiscoveryApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ResourcesDiscoveryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ResourcesDiscoveryApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getResourcesDiscoverCategories
     * @param categoryId A category ID to filter on. (optional)
     * @param with A comma-separated list of submodels to include. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourcesDiscoverCategoriesCall(String categoryId, String with, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/categories";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (categoryId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("category_id", categoryId));
        }

        if (with != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("with", with));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResourcesDiscoverCategoriesValidateBeforeCall(String categoryId, String with, final ApiCallback _callback) throws ApiException {
        return getResourcesDiscoverCategoriesCall(categoryId, with, _callback);

    }

    /**
     * Fetch a list of categories
     * Supported &#39;with&#39; hints:  - Children: includes all subcategories and their children
     * @param categoryId A category ID to filter on. (optional)
     * @param with A comma-separated list of submodels to include. (optional)
     * @return GetResourcesDiscoverCategories200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public GetResourcesDiscoverCategories200Response getResourcesDiscoverCategories(String categoryId, String with) throws ApiException {
        ApiResponse<GetResourcesDiscoverCategories200Response> localVarResp = getResourcesDiscoverCategoriesWithHttpInfo(categoryId, with);
        return localVarResp.getData();
    }

    /**
     * Fetch a list of categories
     * Supported &#39;with&#39; hints:  - Children: includes all subcategories and their children
     * @param categoryId A category ID to filter on. (optional)
     * @param with A comma-separated list of submodels to include. (optional)
     * @return ApiResponse&lt;GetResourcesDiscoverCategories200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetResourcesDiscoverCategories200Response> getResourcesDiscoverCategoriesWithHttpInfo(String categoryId, String with) throws ApiException {
        okhttp3.Call localVarCall = getResourcesDiscoverCategoriesValidateBeforeCall(categoryId, with, null);
        Type localVarReturnType = new TypeToken<GetResourcesDiscoverCategories200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch a list of categories (asynchronously)
     * Supported &#39;with&#39; hints:  - Children: includes all subcategories and their children
     * @param categoryId A category ID to filter on. (optional)
     * @param with A comma-separated list of submodels to include. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourcesDiscoverCategoriesAsync(String categoryId, String with, final ApiCallback<GetResourcesDiscoverCategories200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResourcesDiscoverCategoriesValidateBeforeCall(categoryId, with, _callback);
        Type localVarReturnType = new TypeToken<GetResourcesDiscoverCategories200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getResourcesDiscoverResources
     * @param categoryId A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param filters A list of dynamic filters to apply. (optional)
     * @param resourceIds A comma-separated list of resource IDs to filter on. (optional)
     * @param page The page number to return. (optional, default to 1)
     * @param perPage The number of resources to return per page. (optional, default to 25)
     * @param noDependencies  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourcesDiscoverResourcesCall(String categoryId, String with, Object filters, String resourceIds, Integer page, BigDecimal perPage, Boolean noDependencies, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/resources";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (categoryId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("category_id", categoryId));
        }

        if (with != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("with", with));
        }

        if (filters != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filters", filters));
        }

        if (resourceIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("resource_ids", resourceIds));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        if (noDependencies != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("no_dependencies", noDependencies));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResourcesDiscoverResourcesValidateBeforeCall(String categoryId, String with, Object filters, String resourceIds, Integer page, BigDecimal perPage, Boolean noDependencies, final ApiCallback _callback) throws ApiException {
        return getResourcesDiscoverResourcesCall(categoryId, with, filters, resourceIds, page, perPage, noDependencies, _callback);

    }

    /**
     * Fetch a list of resources
     * Supported &#39;with&#39; hints:  - &#x60;filters&#x60;: include dynamic filter information in the response.  - See &#39;Resource&#39; model for additional &#39;with&#39; hints.
     * @param categoryId A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param filters A list of dynamic filters to apply. (optional)
     * @param resourceIds A comma-separated list of resource IDs to filter on. (optional)
     * @param page The page number to return. (optional, default to 1)
     * @param perPage The number of resources to return per page. (optional, default to 25)
     * @param noDependencies  (optional)
     * @return GetResourcesDiscoverResources200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public GetResourcesDiscoverResources200Response getResourcesDiscoverResources(String categoryId, String with, Object filters, String resourceIds, Integer page, BigDecimal perPage, Boolean noDependencies) throws ApiException {
        ApiResponse<GetResourcesDiscoverResources200Response> localVarResp = getResourcesDiscoverResourcesWithHttpInfo(categoryId, with, filters, resourceIds, page, perPage, noDependencies);
        return localVarResp.getData();
    }

    /**
     * Fetch a list of resources
     * Supported &#39;with&#39; hints:  - &#x60;filters&#x60;: include dynamic filter information in the response.  - See &#39;Resource&#39; model for additional &#39;with&#39; hints.
     * @param categoryId A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param filters A list of dynamic filters to apply. (optional)
     * @param resourceIds A comma-separated list of resource IDs to filter on. (optional)
     * @param page The page number to return. (optional, default to 1)
     * @param perPage The number of resources to return per page. (optional, default to 25)
     * @param noDependencies  (optional)
     * @return ApiResponse&lt;GetResourcesDiscoverResources200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetResourcesDiscoverResources200Response> getResourcesDiscoverResourcesWithHttpInfo(String categoryId, String with, Object filters, String resourceIds, Integer page, BigDecimal perPage, Boolean noDependencies) throws ApiException {
        okhttp3.Call localVarCall = getResourcesDiscoverResourcesValidateBeforeCall(categoryId, with, filters, resourceIds, page, perPage, noDependencies, null);
        Type localVarReturnType = new TypeToken<GetResourcesDiscoverResources200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch a list of resources (asynchronously)
     * Supported &#39;with&#39; hints:  - &#x60;filters&#x60;: include dynamic filter information in the response.  - See &#39;Resource&#39; model for additional &#39;with&#39; hints.
     * @param categoryId A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param filters A list of dynamic filters to apply. (optional)
     * @param resourceIds A comma-separated list of resource IDs to filter on. (optional)
     * @param page The page number to return. (optional, default to 1)
     * @param perPage The number of resources to return per page. (optional, default to 25)
     * @param noDependencies  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourcesDiscoverResourcesAsync(String categoryId, String with, Object filters, String resourceIds, Integer page, BigDecimal perPage, Boolean noDependencies, final ApiCallback<GetResourcesDiscoverResources200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResourcesDiscoverResourcesValidateBeforeCall(categoryId, with, filters, resourceIds, page, perPage, noDependencies, _callback);
        Type localVarReturnType = new TypeToken<GetResourcesDiscoverResources200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getV2ResourcesDiscoverCartView
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesDiscoverCartViewCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/view";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2ResourcesDiscoverCartViewValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getV2ResourcesDiscoverCartViewCall(_callback);

    }

    /**
     * View the user&#39;s cart items
     * 
     * @return GetV2ResourcesDiscoverCartView200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GetV2ResourcesDiscoverCartView200Response getV2ResourcesDiscoverCartView() throws ApiException {
        ApiResponse<GetV2ResourcesDiscoverCartView200Response> localVarResp = getV2ResourcesDiscoverCartViewWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * View the user&#39;s cart items
     * 
     * @return ApiResponse&lt;GetV2ResourcesDiscoverCartView200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetV2ResourcesDiscoverCartView200Response> getV2ResourcesDiscoverCartViewWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getV2ResourcesDiscoverCartViewValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetV2ResourcesDiscoverCartView200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * View the user&#39;s cart items (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesDiscoverCartViewAsync(final ApiCallback<GetV2ResourcesDiscoverCartView200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getV2ResourcesDiscoverCartViewValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetV2ResourcesDiscoverCartView200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getV2ResourcesDiscoverLicenses
     * @param page The page number/offset to return items for. (optional)
     * @param perPage The number of items per page to return. (optional, default to 25)
     * @param with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesDiscoverLicensesCall(Integer page, Integer perPage, String with, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/licenses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        if (with != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("with", with));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2ResourcesDiscoverLicensesValidateBeforeCall(Integer page, Integer perPage, String with, final ApiCallback _callback) throws ApiException {
        return getV2ResourcesDiscoverLicensesCall(page, perPage, with, _callback);

    }

    /**
     * Fetch a list of the user&#39;s licenses
     * Supported &#39;with&#39; hints:  - Resource: the resource the license is for if content_type &#x3D; &#x60;resource&#x60;
     * @param page The page number/offset to return items for. (optional)
     * @param perPage The number of items per page to return. (optional, default to 25)
     * @param with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @return GetV2ResourcesDiscoverLicenses200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public GetV2ResourcesDiscoverLicenses200Response getV2ResourcesDiscoverLicenses(Integer page, Integer perPage, String with) throws ApiException {
        ApiResponse<GetV2ResourcesDiscoverLicenses200Response> localVarResp = getV2ResourcesDiscoverLicensesWithHttpInfo(page, perPage, with);
        return localVarResp.getData();
    }

    /**
     * Fetch a list of the user&#39;s licenses
     * Supported &#39;with&#39; hints:  - Resource: the resource the license is for if content_type &#x3D; &#x60;resource&#x60;
     * @param page The page number/offset to return items for. (optional)
     * @param perPage The number of items per page to return. (optional, default to 25)
     * @param with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @return ApiResponse&lt;GetV2ResourcesDiscoverLicenses200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetV2ResourcesDiscoverLicenses200Response> getV2ResourcesDiscoverLicensesWithHttpInfo(Integer page, Integer perPage, String with) throws ApiException {
        okhttp3.Call localVarCall = getV2ResourcesDiscoverLicensesValidateBeforeCall(page, perPage, with, null);
        Type localVarReturnType = new TypeToken<GetV2ResourcesDiscoverLicenses200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch a list of the user&#39;s licenses (asynchronously)
     * Supported &#39;with&#39; hints:  - Resource: the resource the license is for if content_type &#x3D; &#x60;resource&#x60;
     * @param page The page number/offset to return items for. (optional)
     * @param perPage The number of items per page to return. (optional, default to 25)
     * @param with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 4XX </td><td>  </td><td>  -  </td></tr>
        <tr><td> 5XX </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesDiscoverLicensesAsync(Integer page, Integer perPage, String with, final ApiCallback<GetV2ResourcesDiscoverLicenses200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getV2ResourcesDiscoverLicensesValidateBeforeCall(page, perPage, with, _callback);
        Type localVarReturnType = new TypeToken<GetV2ResourcesDiscoverLicenses200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesDiscoverCartAdd
     * @param postV2ResourcesDiscoverCartAddRequest A list of content to add to the user&#39;s cart. The outer list is keyed by the content type and the inner list are the content IDs.    For instance, if adding a resource with the ID 555, the body becomes:  &#x60;&#x60;&#x60;json  {\&quot;add\&quot;: {\&quot;resource\&quot;: [555]}}  &#x60;&#x60;&#x60; (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 2XX </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartAddCall(PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postV2ResourcesDiscoverCartAddRequest;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesDiscoverCartAddValidateBeforeCall(PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesDiscoverCartAddCall(postV2ResourcesDiscoverCartAddRequest, _callback);

    }

    /**
     * Add items to a user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartAddRequest A list of content to add to the user&#39;s cart. The outer list is keyed by the content type and the inner list are the content IDs.    For instance, if adding a resource with the ID 555, the body becomes:  &#x60;&#x60;&#x60;json  {\&quot;add\&quot;: {\&quot;resource\&quot;: [555]}}  &#x60;&#x60;&#x60; (optional)
     * @return PostV2ResourcesDiscoverCartAdd2XXResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 2XX </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesDiscoverCartAdd2XXResponse postV2ResourcesDiscoverCartAdd(PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest) throws ApiException {
        ApiResponse<PostV2ResourcesDiscoverCartAdd2XXResponse> localVarResp = postV2ResourcesDiscoverCartAddWithHttpInfo(postV2ResourcesDiscoverCartAddRequest);
        return localVarResp.getData();
    }

    /**
     * Add items to a user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartAddRequest A list of content to add to the user&#39;s cart. The outer list is keyed by the content type and the inner list are the content IDs.    For instance, if adding a resource with the ID 555, the body becomes:  &#x60;&#x60;&#x60;json  {\&quot;add\&quot;: {\&quot;resource\&quot;: [555]}}  &#x60;&#x60;&#x60; (optional)
     * @return ApiResponse&lt;PostV2ResourcesDiscoverCartAdd2XXResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 2XX </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesDiscoverCartAdd2XXResponse> postV2ResourcesDiscoverCartAddWithHttpInfo(PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartAddValidateBeforeCall(postV2ResourcesDiscoverCartAddRequest, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartAdd2XXResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add items to a user&#39;s cart (asynchronously)
     * 
     * @param postV2ResourcesDiscoverCartAddRequest A list of content to add to the user&#39;s cart. The outer list is keyed by the content type and the inner list are the content IDs.    For instance, if adding a resource with the ID 555, the body becomes:  &#x60;&#x60;&#x60;json  {\&quot;add\&quot;: {\&quot;resource\&quot;: [555]}}  &#x60;&#x60;&#x60; (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 2XX </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartAddAsync(PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest, final ApiCallback<PostV2ResourcesDiscoverCartAdd2XXResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartAddValidateBeforeCall(postV2ResourcesDiscoverCartAddRequest, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartAdd2XXResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesDiscoverCartCheckout
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCheckoutCall(Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/checkout";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesDiscoverCartCheckoutValidateBeforeCall(Object body, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesDiscoverCartCheckoutCall(body, _callback);

    }

    /**
     * Initiate a checkout of a user&#39;s cart
     * 
     * @param body  (optional)
     * @return PostV2ResourcesDiscoverCartCheckout200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesDiscoverCartCheckout200Response postV2ResourcesDiscoverCartCheckout(Object body) throws ApiException {
        ApiResponse<PostV2ResourcesDiscoverCartCheckout200Response> localVarResp = postV2ResourcesDiscoverCartCheckoutWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * Initiate a checkout of a user&#39;s cart
     * 
     * @param body  (optional)
     * @return ApiResponse&lt;PostV2ResourcesDiscoverCartCheckout200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesDiscoverCartCheckout200Response> postV2ResourcesDiscoverCartCheckoutWithHttpInfo(Object body) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCheckoutValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCheckout200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Initiate a checkout of a user&#39;s cart (asynchronously)
     * 
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCheckoutAsync(Object body, final ApiCallback<PostV2ResourcesDiscoverCartCheckout200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCheckoutValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCheckout200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesDiscoverCartCouponAdd
     * @param postV2ResourcesDiscoverCartCouponAddRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCouponAddCall(PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postV2ResourcesDiscoverCartCouponAddRequest;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/coupon/add";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesDiscoverCartCouponAddValidateBeforeCall(PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesDiscoverCartCouponAddCall(postV2ResourcesDiscoverCartCouponAddRequest, _callback);

    }

    /**
     * Add a coupon to the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartCouponAddRequest  (optional)
     * @return PostV2ResourcesDiscoverCartCouponAdd200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesDiscoverCartCouponAdd200Response postV2ResourcesDiscoverCartCouponAdd(PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest) throws ApiException {
        ApiResponse<PostV2ResourcesDiscoverCartCouponAdd200Response> localVarResp = postV2ResourcesDiscoverCartCouponAddWithHttpInfo(postV2ResourcesDiscoverCartCouponAddRequest);
        return localVarResp.getData();
    }

    /**
     * Add a coupon to the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartCouponAddRequest  (optional)
     * @return ApiResponse&lt;PostV2ResourcesDiscoverCartCouponAdd200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesDiscoverCartCouponAdd200Response> postV2ResourcesDiscoverCartCouponAddWithHttpInfo(PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCouponAddValidateBeforeCall(postV2ResourcesDiscoverCartCouponAddRequest, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCouponAdd200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a coupon to the user&#39;s cart (asynchronously)
     * 
     * @param postV2ResourcesDiscoverCartCouponAddRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCouponAddAsync(PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest, final ApiCallback<PostV2ResourcesDiscoverCartCouponAdd200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCouponAddValidateBeforeCall(postV2ResourcesDiscoverCartCouponAddRequest, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCouponAdd200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesDiscoverCartCouponRemove
     * @param postV2ResourcesDiscoverCartCouponRemoveRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCouponRemoveCall(PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postV2ResourcesDiscoverCartCouponRemoveRequest;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/coupon/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesDiscoverCartCouponRemoveValidateBeforeCall(PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesDiscoverCartCouponRemoveCall(postV2ResourcesDiscoverCartCouponRemoveRequest, _callback);

    }

    /**
     * Remove a coupon from the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartCouponRemoveRequest  (optional)
     * @return PostV2ResourcesDiscoverCartCouponRemove200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesDiscoverCartCouponRemove200Response postV2ResourcesDiscoverCartCouponRemove(PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest) throws ApiException {
        ApiResponse<PostV2ResourcesDiscoverCartCouponRemove200Response> localVarResp = postV2ResourcesDiscoverCartCouponRemoveWithHttpInfo(postV2ResourcesDiscoverCartCouponRemoveRequest);
        return localVarResp.getData();
    }

    /**
     * Remove a coupon from the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartCouponRemoveRequest  (optional)
     * @return ApiResponse&lt;PostV2ResourcesDiscoverCartCouponRemove200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesDiscoverCartCouponRemove200Response> postV2ResourcesDiscoverCartCouponRemoveWithHttpInfo(PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCouponRemoveValidateBeforeCall(postV2ResourcesDiscoverCartCouponRemoveRequest, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCouponRemove200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Remove a coupon from the user&#39;s cart (asynchronously)
     * 
     * @param postV2ResourcesDiscoverCartCouponRemoveRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartCouponRemoveAsync(PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest, final ApiCallback<PostV2ResourcesDiscoverCartCouponRemove200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartCouponRemoveValidateBeforeCall(postV2ResourcesDiscoverCartCouponRemoveRequest, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartCouponRemove200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesDiscoverCartRemove
     * @param postV2ResourcesDiscoverCartRemoveRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartRemoveCall(PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postV2ResourcesDiscoverCartRemoveRequest;

        // create path and map variables
        String localVarPath = "/v2/resources/discover/cart/remove";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesDiscoverCartRemoveValidateBeforeCall(PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesDiscoverCartRemoveCall(postV2ResourcesDiscoverCartRemoveRequest, _callback);

    }

    /**
     * Remove an item from the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartRemoveRequest  (optional)
     * @return PostV2ResourcesDiscoverCartRemove200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesDiscoverCartRemove200Response postV2ResourcesDiscoverCartRemove(PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest) throws ApiException {
        ApiResponse<PostV2ResourcesDiscoverCartRemove200Response> localVarResp = postV2ResourcesDiscoverCartRemoveWithHttpInfo(postV2ResourcesDiscoverCartRemoveRequest);
        return localVarResp.getData();
    }

    /**
     * Remove an item from the user&#39;s cart
     * 
     * @param postV2ResourcesDiscoverCartRemoveRequest  (optional)
     * @return ApiResponse&lt;PostV2ResourcesDiscoverCartRemove200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesDiscoverCartRemove200Response> postV2ResourcesDiscoverCartRemoveWithHttpInfo(PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartRemoveValidateBeforeCall(postV2ResourcesDiscoverCartRemoveRequest, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartRemove200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Remove an item from the user&#39;s cart (asynchronously)
     * 
     * @param postV2ResourcesDiscoverCartRemoveRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesDiscoverCartRemoveAsync(PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest, final ApiCallback<PostV2ResourcesDiscoverCartRemove200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesDiscoverCartRemoveValidateBeforeCall(postV2ResourcesDiscoverCartRemoveRequest, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesDiscoverCartRemove200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
