/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.GetV2ResourcesCreatorCoupons200Response;
import org.openapitools.client.model.GetV2ResourcesCreatorCouponsEntries200Response;
import org.openapitools.client.model.PostV2ResourcesCreatorCoupons200Response;
import org.openapitools.client.model.PostV2ResourcesCreatorCouponsRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ResourcesCreatorCouponsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ResourcesCreatorCouponsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ResourcesCreatorCouponsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getV2ResourcesCreatorCoupons
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesCreatorCouponsCall(List couponIds, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/creator/coupons";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (couponIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("coupon_ids", couponIds));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2ResourcesCreatorCouponsValidateBeforeCall(List couponIds, final ApiCallback _callback) throws ApiException {
        return getV2ResourcesCreatorCouponsCall(couponIds, _callback);

    }

    /**
     * Fetch a list of your coupons
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @return GetV2ResourcesCreatorCoupons200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GetV2ResourcesCreatorCoupons200Response getV2ResourcesCreatorCoupons(List couponIds) throws ApiException {
        ApiResponse<GetV2ResourcesCreatorCoupons200Response> localVarResp = getV2ResourcesCreatorCouponsWithHttpInfo(couponIds);
        return localVarResp.getData();
    }

    /**
     * Fetch a list of your coupons
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @return ApiResponse&lt;GetV2ResourcesCreatorCoupons200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetV2ResourcesCreatorCoupons200Response> getV2ResourcesCreatorCouponsWithHttpInfo(List couponIds) throws ApiException {
        okhttp3.Call localVarCall = getV2ResourcesCreatorCouponsValidateBeforeCall(couponIds, null);
        Type localVarReturnType = new TypeToken<GetV2ResourcesCreatorCoupons200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch a list of your coupons (asynchronously)
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesCreatorCouponsAsync(List couponIds, final ApiCallback<GetV2ResourcesCreatorCoupons200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getV2ResourcesCreatorCouponsValidateBeforeCall(couponIds, _callback);
        Type localVarReturnType = new TypeToken<GetV2ResourcesCreatorCoupons200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getV2ResourcesCreatorCouponsEntries
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesCreatorCouponsEntriesCall(List couponIds, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/resources/creator/coupons/entries";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (couponIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("coupon_ids", couponIds));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2ResourcesCreatorCouponsEntriesValidateBeforeCall(List couponIds, final ApiCallback _callback) throws ApiException {
        return getV2ResourcesCreatorCouponsEntriesCall(couponIds, _callback);

    }

    /**
     * Fetch a list of your coupon entries
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @return GetV2ResourcesCreatorCouponsEntries200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GetV2ResourcesCreatorCouponsEntries200Response getV2ResourcesCreatorCouponsEntries(List couponIds) throws ApiException {
        ApiResponse<GetV2ResourcesCreatorCouponsEntries200Response> localVarResp = getV2ResourcesCreatorCouponsEntriesWithHttpInfo(couponIds);
        return localVarResp.getData();
    }

    /**
     * Fetch a list of your coupon entries
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @return ApiResponse&lt;GetV2ResourcesCreatorCouponsEntries200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetV2ResourcesCreatorCouponsEntries200Response> getV2ResourcesCreatorCouponsEntriesWithHttpInfo(List couponIds) throws ApiException {
        okhttp3.Call localVarCall = getV2ResourcesCreatorCouponsEntriesValidateBeforeCall(couponIds, null);
        Type localVarReturnType = new TypeToken<GetV2ResourcesCreatorCouponsEntries200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch a list of your coupon entries (asynchronously)
     * 
     * @param couponIds A comma-separated list of coupon IDs to filter on. No filter is applied if empty. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getV2ResourcesCreatorCouponsEntriesAsync(List couponIds, final ApiCallback<GetV2ResourcesCreatorCouponsEntries200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getV2ResourcesCreatorCouponsEntriesValidateBeforeCall(couponIds, _callback);
        Type localVarReturnType = new TypeToken<GetV2ResourcesCreatorCouponsEntries200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postV2ResourcesCreatorCoupons
     * @param postV2ResourcesCreatorCouponsRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesCreatorCouponsCall(PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postV2ResourcesCreatorCouponsRequest;

        // create path and map variables
        String localVarPath = "/v2/resources/creator/coupons";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "token" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postV2ResourcesCreatorCouponsValidateBeforeCall(PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest, final ApiCallback _callback) throws ApiException {
        return postV2ResourcesCreatorCouponsCall(postV2ResourcesCreatorCouponsRequest, _callback);

    }

    /**
     * Create a new coupon
     * This endpoint is currently limited to percent-based coupons with a maximum discount of 50%.
     * @param postV2ResourcesCreatorCouponsRequest  (optional)
     * @return PostV2ResourcesCreatorCoupons200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PostV2ResourcesCreatorCoupons200Response postV2ResourcesCreatorCoupons(PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest) throws ApiException {
        ApiResponse<PostV2ResourcesCreatorCoupons200Response> localVarResp = postV2ResourcesCreatorCouponsWithHttpInfo(postV2ResourcesCreatorCouponsRequest);
        return localVarResp.getData();
    }

    /**
     * Create a new coupon
     * This endpoint is currently limited to percent-based coupons with a maximum discount of 50%.
     * @param postV2ResourcesCreatorCouponsRequest  (optional)
     * @return ApiResponse&lt;PostV2ResourcesCreatorCoupons200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostV2ResourcesCreatorCoupons200Response> postV2ResourcesCreatorCouponsWithHttpInfo(PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest) throws ApiException {
        okhttp3.Call localVarCall = postV2ResourcesCreatorCouponsValidateBeforeCall(postV2ResourcesCreatorCouponsRequest, null);
        Type localVarReturnType = new TypeToken<PostV2ResourcesCreatorCoupons200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a new coupon (asynchronously)
     * This endpoint is currently limited to percent-based coupons with a maximum discount of 50%.
     * @param postV2ResourcesCreatorCouponsRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postV2ResourcesCreatorCouponsAsync(PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest, final ApiCallback<PostV2ResourcesCreatorCoupons200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postV2ResourcesCreatorCouponsValidateBeforeCall(postV2ResourcesCreatorCouponsRequest, _callback);
        Type localVarReturnType = new TypeToken<PostV2ResourcesCreatorCoupons200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
