/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Addon
 */
public class AddonTest {
    private final Addon model = new Addon();

    /**
     * Model tests for Addon
     */
    @Test
    public void testAddon() {
        // TODO: test Addon
    }

    /**
     * Test the property 'addonId'
     */
    @Test
    public void addonIdTest() {
        // TODO: test addonId
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'listPrice'
     */
    @Test
    public void listPriceTest() {
        // TODO: test listPrice
    }

    /**
     * Test the property 'listPriceFormatted'
     */
    @Test
    public void listPriceFormattedTest() {
        // TODO: test listPriceFormatted
    }

    /**
     * Test the property 'finalPrice'
     */
    @Test
    public void finalPriceTest() {
        // TODO: test finalPrice
    }

    /**
     * Test the property 'finalPriceFormatted'
     */
    @Test
    public void finalPriceFormattedTest() {
        // TODO: test finalPriceFormatted
    }

    /**
     * Test the property 'priceCurrency'
     */
    @Test
    public void priceCurrencyTest() {
        // TODO: test priceCurrency
    }

    /**
     * Test the property 'displayOrder'
     */
    @Test
    public void displayOrderTest() {
        // TODO: test displayOrder
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

}
