/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Addon;
import org.openapitools.client.model.Bundle;
import org.openapitools.client.model.Coupon;
import org.openapitools.client.model.Resource;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CouponEntry
 */
public class CouponEntryTest {
    private final CouponEntry model = new CouponEntry();

    /**
     * Model tests for CouponEntry
     */
    @Test
    public void testCouponEntry() {
        // TODO: test CouponEntry
    }

    /**
     * Test the property 'entryId'
     */
    @Test
    public void entryIdTest() {
        // TODO: test entryId
    }

    /**
     * Test the property 'couponId'
     */
    @Test
    public void couponIdTest() {
        // TODO: test couponId
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'contentId'
     */
    @Test
    public void contentIdTest() {
        // TODO: test contentId
    }

    /**
     * Test the property 'coupon'
     */
    @Test
    public void couponTest() {
        // TODO: test coupon
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'addon'
     */
    @Test
    public void addonTest() {
        // TODO: test addon
    }

    /**
     * Test the property 'bundle'
     */
    @Test
    public void bundleTest() {
        // TODO: test bundle
    }

}
