/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DownloadRequest
 */
public class DownloadRequestTest {
    private final DownloadRequest model = new DownloadRequest();

    /**
     * Model tests for DownloadRequest
     */
    @Test
    public void testDownloadRequest() {
        // TODO: test DownloadRequest
    }

    /**
     * Test the property 'downloadRequestId'
     */
    @Test
    public void downloadRequestIdTest() {
        // TODO: test downloadRequestId
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'contentId'
     */
    @Test
    public void contentIdTest() {
        // TODO: test contentId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'expires'
     */
    @Test
    public void expiresTest() {
        // TODO: test expires
    }

}
