/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DownloadPlanAction;
import org.openapitools.client.model.DownloadPlanNotice;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DownloadPlan
 */
public class DownloadPlanTest {
    private final DownloadPlan model = new DownloadPlan();

    /**
     * Model tests for DownloadPlan
     */
    @Test
    public void testDownloadPlan() {
        // TODO: test DownloadPlan
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'notices'
     */
    @Test
    public void noticesTest() {
        // TODO: test notices
    }

    /**
     * Test the property 'unsupported'
     */
    @Test
    public void unsupportedTest() {
        // TODO: test unsupported
    }

    /**
     * Test the property 'requiresEmptyServer'
     */
    @Test
    public void requiresEmptyServerTest() {
        // TODO: test requiresEmptyServer
    }

}
