/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetV2AnalyticsSingle200ResponseDataPeriod
 */
public class GetV2AnalyticsSingle200ResponseDataPeriodTest {
    private final GetV2AnalyticsSingle200ResponseDataPeriod model = new GetV2AnalyticsSingle200ResponseDataPeriod();

    /**
     * Model tests for GetV2AnalyticsSingle200ResponseDataPeriod
     */
    @Test
    public void testGetV2AnalyticsSingle200ResponseDataPeriod() {
        // TODO: test GetV2AnalyticsSingle200ResponseDataPeriod
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'periodDisplay'
     */
    @Test
    public void periodDisplayTest() {
        // TODO: test periodDisplay
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

}
