/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListStats;
import org.openapitools.client.model.Store;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetV2ResourcesCreatorStores200ResponseData
 */
public class GetV2ResourcesCreatorStores200ResponseDataTest {
    private final GetV2ResourcesCreatorStores200ResponseData model = new GetV2ResourcesCreatorStores200ResponseData();

    /**
     * Model tests for GetV2ResourcesCreatorStores200ResponseData
     */
    @Test
    public void testGetV2ResourcesCreatorStores200ResponseData() {
        // TODO: test GetV2ResourcesCreatorStores200ResponseData
    }

    /**
     * Test the property 'stores'
     */
    @Test
    public void storesTest() {
        // TODO: test stores
    }

    /**
     * Test the property 'stats'
     */
    @Test
    public void statsTest() {
        // TODO: test stats
    }

}
