/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.License;
import org.openapitools.client.model.ListStats;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetV2ResourcesDiscoverLicenses200ResponseData
 */
public class GetV2ResourcesDiscoverLicenses200ResponseDataTest {
    private final GetV2ResourcesDiscoverLicenses200ResponseData model = new GetV2ResourcesDiscoverLicenses200ResponseData();

    /**
     * Model tests for GetV2ResourcesDiscoverLicenses200ResponseData
     */
    @Test
    public void testGetV2ResourcesDiscoverLicenses200ResponseData() {
        // TODO: test GetV2ResourcesDiscoverLicenses200ResponseData
    }

    /**
     * Test the property 'licenses'
     */
    @Test
    public void licensesTest() {
        // TODO: test licenses
    }

    /**
     * Test the property 'stats'
     */
    @Test
    public void statsTest() {
        // TODO: test stats
    }

}
