/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DownloadRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetV2ResourcesEmbedDownloadInitiate200ResponseData
 */
public class GetV2ResourcesEmbedDownloadInitiate200ResponseDataTest {
    private final GetV2ResourcesEmbedDownloadInitiate200ResponseData model = new GetV2ResourcesEmbedDownloadInitiate200ResponseData();

    /**
     * Model tests for GetV2ResourcesEmbedDownloadInitiate200ResponseData
     */
    @Test
    public void testGetV2ResourcesEmbedDownloadInitiate200ResponseData() {
        // TODO: test GetV2ResourcesEmbedDownloadInitiate200ResponseData
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

}
