/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostV2ResourcesCreatorBatchRequestChangesInner
 */
public class PostV2ResourcesCreatorBatchRequestChangesInnerTest {
    private final PostV2ResourcesCreatorBatchRequestChangesInner model = new PostV2ResourcesCreatorBatchRequestChangesInner();

    /**
     * Model tests for PostV2ResourcesCreatorBatchRequestChangesInner
     */
    @Test
    public void testPostV2ResourcesCreatorBatchRequestChangesInner() {
        // TODO: test PostV2ResourcesCreatorBatchRequestChangesInner
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'search'
     */
    @Test
    public void searchTest() {
        // TODO: test search
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
