/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostV2EventsCompleteRequest
 */
public class PostV2EventsCompleteRequestTest {
    private final PostV2EventsCompleteRequest model = new PostV2EventsCompleteRequest();

    /**
     * Model tests for PostV2EventsCompleteRequest
     */
    @Test
    public void testPostV2EventsCompleteRequest() {
        // TODO: test PostV2EventsCompleteRequest
    }

    /**
     * Test the property 'eventIds'
     */
    @Test
    public void eventIdsTest() {
        // TODO: test eventIds
    }

}
