/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostV2ResourcesDiscoverCartCheckout200ResponseData
 */
public class PostV2ResourcesDiscoverCartCheckout200ResponseDataTest {
    private final PostV2ResourcesDiscoverCartCheckout200ResponseData model = new PostV2ResourcesDiscoverCartCheckout200ResponseData();

    /**
     * Model tests for PostV2ResourcesDiscoverCartCheckout200ResponseData
     */
    @Test
    public void testPostV2ResourcesDiscoverCartCheckout200ResponseData() {
        // TODO: test PostV2ResourcesDiscoverCartCheckout200ResponseData
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'ident'
     */
    @Test
    public void identTest() {
        // TODO: test ident
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
