/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PostV2DeploymentsUpgrade200ResponseDataPreauthorize;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostV2DeploymentsUpgrade200ResponseData
 */
public class PostV2DeploymentsUpgrade200ResponseDataTest {
    private final PostV2DeploymentsUpgrade200ResponseData model = new PostV2DeploymentsUpgrade200ResponseData();

    /**
     * Model tests for PostV2DeploymentsUpgrade200ResponseData
     */
    @Test
    public void testPostV2DeploymentsUpgrade200ResponseData() {
        // TODO: test PostV2DeploymentsUpgrade200ResponseData
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'oauth2Client'
     */
    @Test
    public void oauth2ClientTest() {
        // TODO: test oauth2Client
    }

    /**
     * Test the property 'oauth2Secret'
     */
    @Test
    public void oauth2SecretTest() {
        // TODO: test oauth2Secret
    }

    /**
     * Test the property 'preauthorize'
     */
    @Test
    public void preauthorizeTest() {
        // TODO: test preauthorize
    }

}
