/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostV2ResourcesDiscoverCartRemoveRequest
 */
public class PostV2ResourcesDiscoverCartRemoveRequestTest {
    private final PostV2ResourcesDiscoverCartRemoveRequest model = new PostV2ResourcesDiscoverCartRemoveRequest();

    /**
     * Model tests for PostV2ResourcesDiscoverCartRemoveRequest
     */
    @Test
    public void testPostV2ResourcesDiscoverCartRemoveRequest() {
        // TODO: test PostV2ResourcesDiscoverCartRemoveRequest
    }

    /**
     * Test the property 'cartItemId'
     */
    @Test
    public void cartItemIdTest() {
        // TODO: test cartItemId
    }

}
