/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.Price;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CartItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-26T04:51:56.254296Z[Etc/UTC]")
public class CartItem {
  public static final String SERIALIZED_NAME_CART_ITEM_ID = "cart_item_id";
  @SerializedName(SERIALIZED_NAME_CART_ITEM_ID)
  private String cartItemId;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "content_type";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_CONTENT_ID = "content_id";
  @SerializedName(SERIALIZED_NAME_CONTENT_ID)
  private Integer contentId;

  public static final String SERIALIZED_NAME_CONTENT_TITLE = "content_title";
  @SerializedName(SERIALIZED_NAME_CONTENT_TITLE)
  private String contentTitle;

  public static final String SERIALIZED_NAME_CONTENT_SUMMARY = "content_summary";
  @SerializedName(SERIALIZED_NAME_CONTENT_SUMMARY)
  private String contentSummary;

  public static final String SERIALIZED_NAME_CONTENT_COVER_IMAGE_URL = "content_cover_image_url";
  @SerializedName(SERIALIZED_NAME_CONTENT_COVER_IMAGE_URL)
  private String contentCoverImageUrl;

  public static final String SERIALIZED_NAME_LIST_PRICE = "ListPrice";
  @SerializedName(SERIALIZED_NAME_LIST_PRICE)
  private Price listPrice;

  public static final String SERIALIZED_NAME_FINAL_PRICE = "FinalPrice";
  @SerializedName(SERIALIZED_NAME_FINAL_PRICE)
  private Price finalPrice;

  public static final String SERIALIZED_NAME_DISCOUNTS = "discounts";
  @SerializedName(SERIALIZED_NAME_DISCOUNTS)
  private Map<String, Price> discounts = new HashMap<>();

  public CartItem() {
  }

  public CartItem cartItemId(String cartItemId) {
    this.cartItemId = cartItemId;
    return this;
  }

   /**
   * Get cartItemId
   * @return cartItemId
  **/
  @javax.annotation.Nullable
  public String getCartItemId() {
    return cartItemId;
  }

  public void setCartItemId(String cartItemId) {
    this.cartItemId = cartItemId;
  }


  public CartItem contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @javax.annotation.Nullable
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public CartItem contentId(Integer contentId) {
    this.contentId = contentId;
    return this;
  }

   /**
   * Get contentId
   * @return contentId
  **/
  @javax.annotation.Nullable
  public Integer getContentId() {
    return contentId;
  }

  public void setContentId(Integer contentId) {
    this.contentId = contentId;
  }


  public CartItem contentTitle(String contentTitle) {
    this.contentTitle = contentTitle;
    return this;
  }

   /**
   * Get contentTitle
   * @return contentTitle
  **/
  @javax.annotation.Nullable
  public String getContentTitle() {
    return contentTitle;
  }

  public void setContentTitle(String contentTitle) {
    this.contentTitle = contentTitle;
  }


  public CartItem contentSummary(String contentSummary) {
    this.contentSummary = contentSummary;
    return this;
  }

   /**
   * Get contentSummary
   * @return contentSummary
  **/
  @javax.annotation.Nullable
  public String getContentSummary() {
    return contentSummary;
  }

  public void setContentSummary(String contentSummary) {
    this.contentSummary = contentSummary;
  }


  public CartItem contentCoverImageUrl(String contentCoverImageUrl) {
    this.contentCoverImageUrl = contentCoverImageUrl;
    return this;
  }

   /**
   * Get contentCoverImageUrl
   * @return contentCoverImageUrl
  **/
  @javax.annotation.Nullable
  public String getContentCoverImageUrl() {
    return contentCoverImageUrl;
  }

  public void setContentCoverImageUrl(String contentCoverImageUrl) {
    this.contentCoverImageUrl = contentCoverImageUrl;
  }


  public CartItem listPrice(Price listPrice) {
    this.listPrice = listPrice;
    return this;
  }

   /**
   * Get listPrice
   * @return listPrice
  **/
  @javax.annotation.Nullable
  public Price getListPrice() {
    return listPrice;
  }

  public void setListPrice(Price listPrice) {
    this.listPrice = listPrice;
  }


  public CartItem finalPrice(Price finalPrice) {
    this.finalPrice = finalPrice;
    return this;
  }

   /**
   * Get finalPrice
   * @return finalPrice
  **/
  @javax.annotation.Nullable
  public Price getFinalPrice() {
    return finalPrice;
  }

  public void setFinalPrice(Price finalPrice) {
    this.finalPrice = finalPrice;
  }


  public CartItem discounts(Map<String, Price> discounts) {
    this.discounts = discounts;
    return this;
  }

  public CartItem putDiscountsItem(String key, Price discountsItem) {
    if (this.discounts == null) {
      this.discounts = new HashMap<>();
    }
    this.discounts.put(key, discountsItem);
    return this;
  }

   /**
   * Get discounts
   * @return discounts
  **/
  @javax.annotation.Nullable
  public Map<String, Price> getDiscounts() {
    return discounts;
  }

  public void setDiscounts(Map<String, Price> discounts) {
    this.discounts = discounts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartItem cartItem = (CartItem) o;
    return Objects.equals(this.cartItemId, cartItem.cartItemId) &&
        Objects.equals(this.contentType, cartItem.contentType) &&
        Objects.equals(this.contentId, cartItem.contentId) &&
        Objects.equals(this.contentTitle, cartItem.contentTitle) &&
        Objects.equals(this.contentSummary, cartItem.contentSummary) &&
        Objects.equals(this.contentCoverImageUrl, cartItem.contentCoverImageUrl) &&
        Objects.equals(this.listPrice, cartItem.listPrice) &&
        Objects.equals(this.finalPrice, cartItem.finalPrice) &&
        Objects.equals(this.discounts, cartItem.discounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cartItemId, contentType, contentId, contentTitle, contentSummary, contentCoverImageUrl, listPrice, finalPrice, discounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartItem {\n");
    sb.append("    cartItemId: ").append(toIndentedString(cartItemId)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    contentId: ").append(toIndentedString(contentId)).append("\n");
    sb.append("    contentTitle: ").append(toIndentedString(contentTitle)).append("\n");
    sb.append("    contentSummary: ").append(toIndentedString(contentSummary)).append("\n");
    sb.append("    contentCoverImageUrl: ").append(toIndentedString(contentCoverImageUrl)).append("\n");
    sb.append("    listPrice: ").append(toIndentedString(listPrice)).append("\n");
    sb.append("    finalPrice: ").append(toIndentedString(finalPrice)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cart_item_id");
    openapiFields.add("content_type");
    openapiFields.add("content_id");
    openapiFields.add("content_title");
    openapiFields.add("content_summary");
    openapiFields.add("content_cover_image_url");
    openapiFields.add("ListPrice");
    openapiFields.add("FinalPrice");
    openapiFields.add("discounts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CartItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CartItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CartItem is not found in the empty JSON string", CartItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CartItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CartItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cart_item_id") != null && !jsonObj.get("cart_item_id").isJsonNull()) && !jsonObj.get("cart_item_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cart_item_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cart_item_id").toString()));
      }
      if ((jsonObj.get("content_type") != null && !jsonObj.get("content_type").isJsonNull()) && !jsonObj.get("content_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content_type").toString()));
      }
      if ((jsonObj.get("content_title") != null && !jsonObj.get("content_title").isJsonNull()) && !jsonObj.get("content_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content_title").toString()));
      }
      if ((jsonObj.get("content_summary") != null && !jsonObj.get("content_summary").isJsonNull()) && !jsonObj.get("content_summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content_summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content_summary").toString()));
      }
      if ((jsonObj.get("content_cover_image_url") != null && !jsonObj.get("content_cover_image_url").isJsonNull()) && !jsonObj.get("content_cover_image_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content_cover_image_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content_cover_image_url").toString()));
      }
      // validate the optional field `ListPrice`
      if (jsonObj.get("ListPrice") != null && !jsonObj.get("ListPrice").isJsonNull()) {
        Price.validateJsonElement(jsonObj.get("ListPrice"));
      }
      // validate the optional field `FinalPrice`
      if (jsonObj.get("FinalPrice") != null && !jsonObj.get("FinalPrice").isJsonNull()) {
        Price.validateJsonElement(jsonObj.get("FinalPrice"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CartItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CartItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CartItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CartItem.class));

       return (TypeAdapter<T>) new TypeAdapter<CartItem>() {
           @Override
           public void write(JsonWriter out, CartItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CartItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CartItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CartItem
  * @throws IOException if the JSON string is invalid with respect to CartItem
  */
  public static CartItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CartItem.class);
  }

 /**
  * Convert an instance of CartItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

