/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DownloadPlanAction;
import org.openapitools.client.model.DownloadPlanNotice;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DownloadPlan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T15:23:13.439118Z[Etc/UTC]")
public class DownloadPlan {
  /**
   * Gets or Sets level
   */
  @JsonAdapter(LevelEnum.Adapter.class)
  public enum LevelEnum {
    FULL("full"),
    
    PARTIAL("partial"),
    
    MANUAL("manual");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LevelEnum fromValue(String value) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LevelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      LevelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  private LevelEnum level;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<DownloadPlanAction> actions;

  public static final String SERIALIZED_NAME_NOTICES = "notices";
  @SerializedName(SERIALIZED_NAME_NOTICES)
  private List<DownloadPlanNotice> notices;

  public static final String SERIALIZED_NAME_UNSUPPORTED = "unsupported";
  @SerializedName(SERIALIZED_NAME_UNSUPPORTED)
  private List<String> unsupported;

  public static final String SERIALIZED_NAME_REQUIRES_EMPTY_SERVER = "requires_empty_server";
  @SerializedName(SERIALIZED_NAME_REQUIRES_EMPTY_SERVER)
  private String requiresEmptyServer;

  public DownloadPlan() {
  }

  public DownloadPlan level(LevelEnum level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nonnull
  public LevelEnum getLevel() {
    return level;
  }

  public void setLevel(LevelEnum level) {
    this.level = level;
  }


  public DownloadPlan actions(List<DownloadPlanAction> actions) {
    this.actions = actions;
    return this;
  }

  public DownloadPlan addActionsItem(DownloadPlanAction actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  public List<DownloadPlanAction> getActions() {
    return actions;
  }

  public void setActions(List<DownloadPlanAction> actions) {
    this.actions = actions;
  }


  public DownloadPlan notices(List<DownloadPlanNotice> notices) {
    this.notices = notices;
    return this;
  }

  public DownloadPlan addNoticesItem(DownloadPlanNotice noticesItem) {
    if (this.notices == null) {
      this.notices = new ArrayList<>();
    }
    this.notices.add(noticesItem);
    return this;
  }

   /**
   * Get notices
   * @return notices
  **/
  @javax.annotation.Nullable
  public List<DownloadPlanNotice> getNotices() {
    return notices;
  }

  public void setNotices(List<DownloadPlanNotice> notices) {
    this.notices = notices;
  }


  public DownloadPlan unsupported(List<String> unsupported) {
    this.unsupported = unsupported;
    return this;
  }

  public DownloadPlan addUnsupportedItem(String unsupportedItem) {
    if (this.unsupported == null) {
      this.unsupported = new ArrayList<>();
    }
    this.unsupported.add(unsupportedItem);
    return this;
  }

   /**
   * A list of features which were unsupported (not passed into the &#39;supported&#39; query paramter) which were needed, resulting in the plan level being downgraded to &#39;manual&#39;.
   * @return unsupported
  **/
  @javax.annotation.Nullable
  public List<String> getUnsupported() {
    return unsupported;
  }

  public void setUnsupported(List<String> unsupported) {
    this.unsupported = unsupported;
  }


  public DownloadPlan requiresEmptyServer(String requiresEmptyServer) {
    this.requiresEmptyServer = requiresEmptyServer;
    return this;
  }

   /**
   * Whether the server files must be empty before exeucting the plan steps.
   * @return requiresEmptyServer
  **/
  @javax.annotation.Nullable
  public String getRequiresEmptyServer() {
    return requiresEmptyServer;
  }

  public void setRequiresEmptyServer(String requiresEmptyServer) {
    this.requiresEmptyServer = requiresEmptyServer;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadPlan downloadPlan = (DownloadPlan) o;
    return Objects.equals(this.level, downloadPlan.level) &&
        Objects.equals(this.actions, downloadPlan.actions) &&
        Objects.equals(this.notices, downloadPlan.notices) &&
        Objects.equals(this.unsupported, downloadPlan.unsupported) &&
        Objects.equals(this.requiresEmptyServer, downloadPlan.requiresEmptyServer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, actions, notices, unsupported, requiresEmptyServer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadPlan {\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    notices: ").append(toIndentedString(notices)).append("\n");
    sb.append("    unsupported: ").append(toIndentedString(unsupported)).append("\n");
    sb.append("    requiresEmptyServer: ").append(toIndentedString(requiresEmptyServer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("level");
    openapiFields.add("actions");
    openapiFields.add("notices");
    openapiFields.add("unsupported");
    openapiFields.add("requires_empty_server");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("level");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DownloadPlan
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DownloadPlan.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DownloadPlan is not found in the empty JSON string", DownloadPlan.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DownloadPlan.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DownloadPlan` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DownloadPlan.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("level").toString()));
      }
      // validate the required field `level`
      LevelEnum.validateJsonElement(jsonObj.get("level"));
      if (jsonObj.get("actions") != null && !jsonObj.get("actions").isJsonNull()) {
        JsonArray jsonArrayactions = jsonObj.getAsJsonArray("actions");
        if (jsonArrayactions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("actions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `actions` to be an array in the JSON string but got `%s`", jsonObj.get("actions").toString()));
          }

          // validate the optional field `actions` (array)
          for (int i = 0; i < jsonArrayactions.size(); i++) {
            DownloadPlanAction.validateJsonElement(jsonArrayactions.get(i));
          };
        }
      }
      if (jsonObj.get("notices") != null && !jsonObj.get("notices").isJsonNull()) {
        JsonArray jsonArraynotices = jsonObj.getAsJsonArray("notices");
        if (jsonArraynotices != null) {
          // ensure the json data is an array
          if (!jsonObj.get("notices").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `notices` to be an array in the JSON string but got `%s`", jsonObj.get("notices").toString()));
          }

          // validate the optional field `notices` (array)
          for (int i = 0; i < jsonArraynotices.size(); i++) {
            DownloadPlanNotice.validateJsonElement(jsonArraynotices.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("unsupported") != null && !jsonObj.get("unsupported").isJsonNull() && !jsonObj.get("unsupported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `unsupported` to be an array in the JSON string but got `%s`", jsonObj.get("unsupported").toString()));
      }
      if ((jsonObj.get("requires_empty_server") != null && !jsonObj.get("requires_empty_server").isJsonNull()) && !jsonObj.get("requires_empty_server").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requires_empty_server` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requires_empty_server").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DownloadPlan.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DownloadPlan' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DownloadPlan> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DownloadPlan.class));

       return (TypeAdapter<T>) new TypeAdapter<DownloadPlan>() {
           @Override
           public void write(JsonWriter out, DownloadPlan value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DownloadPlan read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DownloadPlan given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DownloadPlan
  * @throws IOException if the JSON string is invalid with respect to DownloadPlan
  */
  public static DownloadPlan fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DownloadPlan.class);
  }

 /**
  * Convert an instance of DownloadPlan to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

