/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Batch;
import org.openapitools.client.model.ListStats;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetV2ResourcesCreatorBatch200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T10:35:05.977799Z[Etc/UTC]")
public class GetV2ResourcesCreatorBatch200ResponseData {
  public static final String SERIALIZED_NAME_BATCHES = "batches";
  @SerializedName(SERIALIZED_NAME_BATCHES)
  private List<Batch> batches;

  public static final String SERIALIZED_NAME_STATS = "stats";
  @SerializedName(SERIALIZED_NAME_STATS)
  private ListStats stats;

  public GetV2ResourcesCreatorBatch200ResponseData() {
  }

  public GetV2ResourcesCreatorBatch200ResponseData batches(List<Batch> batches) {
    this.batches = batches;
    return this;
  }

  public GetV2ResourcesCreatorBatch200ResponseData addBatchesItem(Batch batchesItem) {
    if (this.batches == null) {
      this.batches = new ArrayList<>();
    }
    this.batches.add(batchesItem);
    return this;
  }

   /**
   * Get batches
   * @return batches
  **/
  @javax.annotation.Nullable
  public List<Batch> getBatches() {
    return batches;
  }

  public void setBatches(List<Batch> batches) {
    this.batches = batches;
  }


  public GetV2ResourcesCreatorBatch200ResponseData stats(ListStats stats) {
    this.stats = stats;
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/
  @javax.annotation.Nullable
  public ListStats getStats() {
    return stats;
  }

  public void setStats(ListStats stats) {
    this.stats = stats;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetV2ResourcesCreatorBatch200ResponseData getV2ResourcesCreatorBatch200ResponseData = (GetV2ResourcesCreatorBatch200ResponseData) o;
    return Objects.equals(this.batches, getV2ResourcesCreatorBatch200ResponseData.batches) &&
        Objects.equals(this.stats, getV2ResourcesCreatorBatch200ResponseData.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batches, stats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetV2ResourcesCreatorBatch200ResponseData {\n");
    sb.append("    batches: ").append(toIndentedString(batches)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("batches");
    openapiFields.add("stats");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetV2ResourcesCreatorBatch200ResponseData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetV2ResourcesCreatorBatch200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetV2ResourcesCreatorBatch200ResponseData is not found in the empty JSON string", GetV2ResourcesCreatorBatch200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetV2ResourcesCreatorBatch200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetV2ResourcesCreatorBatch200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("batches") != null && !jsonObj.get("batches").isJsonNull()) {
        JsonArray jsonArraybatches = jsonObj.getAsJsonArray("batches");
        if (jsonArraybatches != null) {
          // ensure the json data is an array
          if (!jsonObj.get("batches").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `batches` to be an array in the JSON string but got `%s`", jsonObj.get("batches").toString()));
          }

          // validate the optional field `batches` (array)
          for (int i = 0; i < jsonArraybatches.size(); i++) {
            Batch.validateJsonElement(jsonArraybatches.get(i));
          };
        }
      }
      // validate the optional field `stats`
      if (jsonObj.get("stats") != null && !jsonObj.get("stats").isJsonNull()) {
        ListStats.validateJsonElement(jsonObj.get("stats"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetV2ResourcesCreatorBatch200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetV2ResourcesCreatorBatch200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetV2ResourcesCreatorBatch200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetV2ResourcesCreatorBatch200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<GetV2ResourcesCreatorBatch200ResponseData>() {
           @Override
           public void write(JsonWriter out, GetV2ResourcesCreatorBatch200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetV2ResourcesCreatorBatch200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetV2ResourcesCreatorBatch200ResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetV2ResourcesCreatorBatch200ResponseData
  * @throws IOException if the JSON string is invalid with respect to GetV2ResourcesCreatorBatch200ResponseData
  */
  public static GetV2ResourcesCreatorBatch200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetV2ResourcesCreatorBatch200ResponseData.class);
  }

 /**
  * Convert an instance of GetV2ResourcesCreatorBatch200ResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

