/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostV2ResourcesCreatorCouponsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-02T04:52:01.182854Z[Etc/UTC]")
public class PostV2ResourcesCreatorCouponsRequest {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  private BigDecimal discount;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_DO_EXPIRY = "do_expiry";
  @SerializedName(SERIALIZED_NAME_DO_EXPIRY)
  private Boolean doExpiry;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiry_date";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  private String expiryDate;

  public static final String SERIALIZED_NAME_LIMITED_USES = "limited_uses";
  @SerializedName(SERIALIZED_NAME_LIMITED_USES)
  private Boolean limitedUses;

  public static final String SERIALIZED_NAME_MAX_USES = "max_uses";
  @SerializedName(SERIALIZED_NAME_MAX_USES)
  private Integer maxUses;

  public static final String SERIALIZED_NAME_LIMITED_USER_USES = "limited_user_uses";
  @SerializedName(SERIALIZED_NAME_LIMITED_USER_USES)
  private Boolean limitedUserUses;

  public static final String SERIALIZED_NAME_MAX_PER_USER_USES = "max_per_user_uses";
  @SerializedName(SERIALIZED_NAME_MAX_PER_USER_USES)
  private Integer maxPerUserUses;

  public static final String SERIALIZED_NAME_ALL_CONTENT_TYPES = "all_content_types";
  @SerializedName(SERIALIZED_NAME_ALL_CONTENT_TYPES)
  private List<String> allContentTypes;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private String resources;

  public static final String SERIALIZED_NAME_ADDONS = "addons";
  @SerializedName(SERIALIZED_NAME_ADDONS)
  private String addons;

  public static final String SERIALIZED_NAME_BUNDLES = "bundles";
  @SerializedName(SERIALIZED_NAME_BUNDLES)
  private String bundles;

  public PostV2ResourcesCreatorCouponsRequest() {
  }

  public PostV2ResourcesCreatorCouponsRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Must be &#39;perecent&#39;.
   * @return type
  **/
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  public PostV2ResourcesCreatorCouponsRequest discount(BigDecimal discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * minimum: 1
   * maximum: 50
   * @return discount
  **/
  @javax.annotation.Nonnull
  public BigDecimal getDiscount() {
    return discount;
  }

  public void setDiscount(BigDecimal discount) {
    this.discount = discount;
  }


  public PostV2ResourcesCreatorCouponsRequest label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The trailing part of the coupon code (without &#39;{user_id}-&#39;).
   * @return label
  **/
  @javax.annotation.Nonnull
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  public PostV2ResourcesCreatorCouponsRequest doExpiry(Boolean doExpiry) {
    this.doExpiry = doExpiry;
    return this;
  }

   /**
   * Whether or not to respect the &#39;expiry_date&#39; field. No expiry date is set otherwise.
   * @return doExpiry
  **/
  @javax.annotation.Nullable
  public Boolean getDoExpiry() {
    return doExpiry;
  }

  public void setDoExpiry(Boolean doExpiry) {
    this.doExpiry = doExpiry;
  }


  public PostV2ResourcesCreatorCouponsRequest expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @javax.annotation.Nullable
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }


  public PostV2ResourcesCreatorCouponsRequest limitedUses(Boolean limitedUses) {
    this.limitedUses = limitedUses;
    return this;
  }

   /**
   * Whether or not to respect the &#39;max_uses&#39; field. No max use limit is set otherwise.
   * @return limitedUses
  **/
  @javax.annotation.Nullable
  public Boolean getLimitedUses() {
    return limitedUses;
  }

  public void setLimitedUses(Boolean limitedUses) {
    this.limitedUses = limitedUses;
  }


  public PostV2ResourcesCreatorCouponsRequest maxUses(Integer maxUses) {
    this.maxUses = maxUses;
    return this;
  }

   /**
   * Get maxUses
   * @return maxUses
  **/
  @javax.annotation.Nullable
  public Integer getMaxUses() {
    return maxUses;
  }

  public void setMaxUses(Integer maxUses) {
    this.maxUses = maxUses;
  }


  public PostV2ResourcesCreatorCouponsRequest limitedUserUses(Boolean limitedUserUses) {
    this.limitedUserUses = limitedUserUses;
    return this;
  }

   /**
   * Whether or not to respect the &#39;max_per_user_uses&#39; field. No max uses per user limit is set otherwise.
   * @return limitedUserUses
  **/
  @javax.annotation.Nullable
  public Boolean getLimitedUserUses() {
    return limitedUserUses;
  }

  public void setLimitedUserUses(Boolean limitedUserUses) {
    this.limitedUserUses = limitedUserUses;
  }


  public PostV2ResourcesCreatorCouponsRequest maxPerUserUses(Integer maxPerUserUses) {
    this.maxPerUserUses = maxPerUserUses;
    return this;
  }

   /**
   * Get maxPerUserUses
   * @return maxPerUserUses
  **/
  @javax.annotation.Nullable
  public Integer getMaxPerUserUses() {
    return maxPerUserUses;
  }

  public void setMaxPerUserUses(Integer maxPerUserUses) {
    this.maxPerUserUses = maxPerUserUses;
  }


  public PostV2ResourcesCreatorCouponsRequest allContentTypes(List<String> allContentTypes) {
    this.allContentTypes = allContentTypes;
    return this;
  }

  public PostV2ResourcesCreatorCouponsRequest addAllContentTypesItem(String allContentTypesItem) {
    if (this.allContentTypes == null) {
      this.allContentTypes = new ArrayList<>();
    }
    this.allContentTypes.add(allContentTypesItem);
    return this;
  }

   /**
   * If a content type is included, all of the creator&#39;s content (of that type) can be used against this coupon.  Support values include: &#39;resource&#39;, &#39;addon&#39;, and &#39;bundle&#39;
   * @return allContentTypes
  **/
  @javax.annotation.Nullable
  public List<String> getAllContentTypes() {
    return allContentTypes;
  }

  public void setAllContentTypes(List<String> allContentTypes) {
    this.allContentTypes = allContentTypes;
  }


  public PostV2ResourcesCreatorCouponsRequest resources(String resources) {
    this.resources = resources;
    return this;
  }

   /**
   * A comma-separated list of resource IDs which this coupon can be used against.
   * @return resources
  **/
  @javax.annotation.Nullable
  public String getResources() {
    return resources;
  }

  public void setResources(String resources) {
    this.resources = resources;
  }


  public PostV2ResourcesCreatorCouponsRequest addons(String addons) {
    this.addons = addons;
    return this;
  }

   /**
   * A comma-separated list of addon IDs which this coupon can be used against.
   * @return addons
  **/
  @javax.annotation.Nullable
  public String getAddons() {
    return addons;
  }

  public void setAddons(String addons) {
    this.addons = addons;
  }


  public PostV2ResourcesCreatorCouponsRequest bundles(String bundles) {
    this.bundles = bundles;
    return this;
  }

   /**
   * A comma-separated list of bundle IDs which this coupon can be used against.
   * @return bundles
  **/
  @javax.annotation.Nullable
  public String getBundles() {
    return bundles;
  }

  public void setBundles(String bundles) {
    this.bundles = bundles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2ResourcesCreatorCouponsRequest postV2ResourcesCreatorCouponsRequest = (PostV2ResourcesCreatorCouponsRequest) o;
    return Objects.equals(this.type, postV2ResourcesCreatorCouponsRequest.type) &&
        Objects.equals(this.discount, postV2ResourcesCreatorCouponsRequest.discount) &&
        Objects.equals(this.label, postV2ResourcesCreatorCouponsRequest.label) &&
        Objects.equals(this.doExpiry, postV2ResourcesCreatorCouponsRequest.doExpiry) &&
        Objects.equals(this.expiryDate, postV2ResourcesCreatorCouponsRequest.expiryDate) &&
        Objects.equals(this.limitedUses, postV2ResourcesCreatorCouponsRequest.limitedUses) &&
        Objects.equals(this.maxUses, postV2ResourcesCreatorCouponsRequest.maxUses) &&
        Objects.equals(this.limitedUserUses, postV2ResourcesCreatorCouponsRequest.limitedUserUses) &&
        Objects.equals(this.maxPerUserUses, postV2ResourcesCreatorCouponsRequest.maxPerUserUses) &&
        Objects.equals(this.allContentTypes, postV2ResourcesCreatorCouponsRequest.allContentTypes) &&
        Objects.equals(this.resources, postV2ResourcesCreatorCouponsRequest.resources) &&
        Objects.equals(this.addons, postV2ResourcesCreatorCouponsRequest.addons) &&
        Objects.equals(this.bundles, postV2ResourcesCreatorCouponsRequest.bundles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, discount, label, doExpiry, expiryDate, limitedUses, maxUses, limitedUserUses, maxPerUserUses, allContentTypes, resources, addons, bundles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2ResourcesCreatorCouponsRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    doExpiry: ").append(toIndentedString(doExpiry)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    limitedUses: ").append(toIndentedString(limitedUses)).append("\n");
    sb.append("    maxUses: ").append(toIndentedString(maxUses)).append("\n");
    sb.append("    limitedUserUses: ").append(toIndentedString(limitedUserUses)).append("\n");
    sb.append("    maxPerUserUses: ").append(toIndentedString(maxPerUserUses)).append("\n");
    sb.append("    allContentTypes: ").append(toIndentedString(allContentTypes)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    addons: ").append(toIndentedString(addons)).append("\n");
    sb.append("    bundles: ").append(toIndentedString(bundles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("discount");
    openapiFields.add("label");
    openapiFields.add("do_expiry");
    openapiFields.add("expiry_date");
    openapiFields.add("limited_uses");
    openapiFields.add("max_uses");
    openapiFields.add("limited_user_uses");
    openapiFields.add("max_per_user_uses");
    openapiFields.add("all_content_types");
    openapiFields.add("resources");
    openapiFields.add("addons");
    openapiFields.add("bundles");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("discount");
    openapiRequiredFields.add("label");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PostV2ResourcesCreatorCouponsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV2ResourcesCreatorCouponsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV2ResourcesCreatorCouponsRequest is not found in the empty JSON string", PostV2ResourcesCreatorCouponsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV2ResourcesCreatorCouponsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV2ResourcesCreatorCouponsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostV2ResourcesCreatorCouponsRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("expiry_date") != null && !jsonObj.get("expiry_date").isJsonNull()) && !jsonObj.get("expiry_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiry_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiry_date").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("all_content_types") != null && !jsonObj.get("all_content_types").isJsonNull() && !jsonObj.get("all_content_types").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `all_content_types` to be an array in the JSON string but got `%s`", jsonObj.get("all_content_types").toString()));
      }
      if ((jsonObj.get("resources") != null && !jsonObj.get("resources").isJsonNull()) && !jsonObj.get("resources").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resources` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resources").toString()));
      }
      if ((jsonObj.get("addons") != null && !jsonObj.get("addons").isJsonNull()) && !jsonObj.get("addons").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addons` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addons").toString()));
      }
      if ((jsonObj.get("bundles") != null && !jsonObj.get("bundles").isJsonNull()) && !jsonObj.get("bundles").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bundles` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bundles").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV2ResourcesCreatorCouponsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV2ResourcesCreatorCouponsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV2ResourcesCreatorCouponsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV2ResourcesCreatorCouponsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV2ResourcesCreatorCouponsRequest>() {
           @Override
           public void write(JsonWriter out, PostV2ResourcesCreatorCouponsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV2ResourcesCreatorCouponsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostV2ResourcesCreatorCouponsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostV2ResourcesCreatorCouponsRequest
  * @throws IOException if the JSON string is invalid with respect to PostV2ResourcesCreatorCouponsRequest
  */
  public static PostV2ResourcesCreatorCouponsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV2ResourcesCreatorCouponsRequest.class);
  }

 /**
  * Convert an instance of PostV2ResourcesCreatorCouponsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

