/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PostV2ResourcesCreatorUpdateRequestFile;
import org.openapitools.client.model.PostV2ResourcesCreatorUpdateRequestUpdate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostV2ResourcesCreatorUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-09T04:24:48.610685Z[Etc/UTC]")
public class PostV2ResourcesCreatorUpdateRequest {
  public static final String SERIALIZED_NAME_RESOURCE_ID = "resource_id";
  @SerializedName(SERIALIZED_NAME_RESOURCE_ID)
  private Integer resourceId;

  public static final String SERIALIZED_NAME_VERSION_NAME = "version_name";
  @SerializedName(SERIALIZED_NAME_VERSION_NAME)
  private String versionName;

  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  private PostV2ResourcesCreatorUpdateRequestFile _file;

  public static final String SERIALIZED_NAME_UPDATE = "update";
  @SerializedName(SERIALIZED_NAME_UPDATE)
  private PostV2ResourcesCreatorUpdateRequestUpdate update;

  public PostV2ResourcesCreatorUpdateRequest() {
  }

  public PostV2ResourcesCreatorUpdateRequest resourceId(Integer resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @javax.annotation.Nonnull
  public Integer getResourceId() {
    return resourceId;
  }

  public void setResourceId(Integer resourceId) {
    this.resourceId = resourceId;
  }


  public PostV2ResourcesCreatorUpdateRequest versionName(String versionName) {
    this.versionName = versionName;
    return this;
  }

   /**
   * The version name as a string (eg. 5.0, 5.0-stable). The final version name will be prepended with &#39;v&#39; (eg. v5.0, v5.0-stable).
   * @return versionName
  **/
  @javax.annotation.Nonnull
  public String getVersionName() {
    return versionName;
  }

  public void setVersionName(String versionName) {
    this.versionName = versionName;
  }


  public PostV2ResourcesCreatorUpdateRequest _file(PostV2ResourcesCreatorUpdateRequestFile _file) {
    this._file = _file;
    return this;
  }

   /**
   * Get _file
   * @return _file
  **/
  @javax.annotation.Nonnull
  public PostV2ResourcesCreatorUpdateRequestFile getFile() {
    return _file;
  }

  public void setFile(PostV2ResourcesCreatorUpdateRequestFile _file) {
    this._file = _file;
  }


  public PostV2ResourcesCreatorUpdateRequest update(PostV2ResourcesCreatorUpdateRequestUpdate update) {
    this.update = update;
    return this;
  }

   /**
   * Get update
   * @return update
  **/
  @javax.annotation.Nullable
  public PostV2ResourcesCreatorUpdateRequestUpdate getUpdate() {
    return update;
  }

  public void setUpdate(PostV2ResourcesCreatorUpdateRequestUpdate update) {
    this.update = update;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2ResourcesCreatorUpdateRequest postV2ResourcesCreatorUpdateRequest = (PostV2ResourcesCreatorUpdateRequest) o;
    return Objects.equals(this.resourceId, postV2ResourcesCreatorUpdateRequest.resourceId) &&
        Objects.equals(this.versionName, postV2ResourcesCreatorUpdateRequest.versionName) &&
        Objects.equals(this._file, postV2ResourcesCreatorUpdateRequest._file) &&
        Objects.equals(this.update, postV2ResourcesCreatorUpdateRequest.update);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceId, versionName, _file, update);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2ResourcesCreatorUpdateRequest {\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("resource_id");
    openapiFields.add("version_name");
    openapiFields.add("file");
    openapiFields.add("update");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("resource_id");
    openapiRequiredFields.add("version_name");
    openapiRequiredFields.add("file");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PostV2ResourcesCreatorUpdateRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV2ResourcesCreatorUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV2ResourcesCreatorUpdateRequest is not found in the empty JSON string", PostV2ResourcesCreatorUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV2ResourcesCreatorUpdateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV2ResourcesCreatorUpdateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostV2ResourcesCreatorUpdateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("version_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version_name").toString()));
      }
      // validate the required field `file`
      PostV2ResourcesCreatorUpdateRequestFile.validateJsonElement(jsonObj.get("file"));
      // validate the optional field `update`
      if (jsonObj.get("update") != null && !jsonObj.get("update").isJsonNull()) {
        PostV2ResourcesCreatorUpdateRequestUpdate.validateJsonElement(jsonObj.get("update"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV2ResourcesCreatorUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV2ResourcesCreatorUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV2ResourcesCreatorUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV2ResourcesCreatorUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV2ResourcesCreatorUpdateRequest>() {
           @Override
           public void write(JsonWriter out, PostV2ResourcesCreatorUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV2ResourcesCreatorUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostV2ResourcesCreatorUpdateRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostV2ResourcesCreatorUpdateRequest
  * @throws IOException if the JSON string is invalid with respect to PostV2ResourcesCreatorUpdateRequest
  */
  public static PostV2ResourcesCreatorUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV2ResourcesCreatorUpdateRequest.class);
  }

 /**
  * Convert an instance of PostV2ResourcesCreatorUpdateRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

