/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostV2ResourcesDiscoverCartRemoveRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-14T13:44:20.000766Z[Etc/UTC]")
public class PostV2ResourcesDiscoverCartRemoveRequest {
  public static final String SERIALIZED_NAME_CART_ITEM_ID = "cart_item_id";
  @SerializedName(SERIALIZED_NAME_CART_ITEM_ID)
  private Integer cartItemId;

  public PostV2ResourcesDiscoverCartRemoveRequest() {
  }

  public PostV2ResourcesDiscoverCartRemoveRequest cartItemId(Integer cartItemId) {
    this.cartItemId = cartItemId;
    return this;
  }

   /**
   * Get cartItemId
   * @return cartItemId
  **/
  @javax.annotation.Nullable
  public Integer getCartItemId() {
    return cartItemId;
  }

  public void setCartItemId(Integer cartItemId) {
    this.cartItemId = cartItemId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest = (PostV2ResourcesDiscoverCartRemoveRequest) o;
    return Objects.equals(this.cartItemId, postV2ResourcesDiscoverCartRemoveRequest.cartItemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cartItemId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2ResourcesDiscoverCartRemoveRequest {\n");
    sb.append("    cartItemId: ").append(toIndentedString(cartItemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cart_item_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PostV2ResourcesDiscoverCartRemoveRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV2ResourcesDiscoverCartRemoveRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV2ResourcesDiscoverCartRemoveRequest is not found in the empty JSON string", PostV2ResourcesDiscoverCartRemoveRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV2ResourcesDiscoverCartRemoveRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV2ResourcesDiscoverCartRemoveRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV2ResourcesDiscoverCartRemoveRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV2ResourcesDiscoverCartRemoveRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV2ResourcesDiscoverCartRemoveRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV2ResourcesDiscoverCartRemoveRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV2ResourcesDiscoverCartRemoveRequest>() {
           @Override
           public void write(JsonWriter out, PostV2ResourcesDiscoverCartRemoveRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV2ResourcesDiscoverCartRemoveRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostV2ResourcesDiscoverCartRemoveRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostV2ResourcesDiscoverCartRemoveRequest
  * @throws IOException if the JSON string is invalid with respect to PostV2ResourcesDiscoverCartRemoveRequest
  */
  public static PostV2ResourcesDiscoverCartRemoveRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV2ResourcesDiscoverCartRemoveRequest.class);
  }

 /**
  * Convert an instance of PostV2ResourcesDiscoverCartRemoveRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

