/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostV2ResourcesCreatorAddonsUpdateRequestFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-01T20:29:13.832214Z[Etc/UTC]")
public class PostV2ResourcesCreatorAddonsUpdateRequestFile {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private String data;

  public PostV2ResourcesCreatorAddonsUpdateRequestFile() {
  }

  public PostV2ResourcesCreatorAddonsUpdateRequestFile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the file (including extension).
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public PostV2ResourcesCreatorAddonsUpdateRequestFile data(String data) {
    this.data = data;
    return this;
  }

   /**
   * The base64 encoded file data.
   * @return data
  **/
  @javax.annotation.Nonnull
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2ResourcesCreatorAddonsUpdateRequestFile postV2ResourcesCreatorAddonsUpdateRequestFile = (PostV2ResourcesCreatorAddonsUpdateRequestFile) o;
    return Objects.equals(this.name, postV2ResourcesCreatorAddonsUpdateRequestFile.name) &&
        Objects.equals(this.data, postV2ResourcesCreatorAddonsUpdateRequestFile.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2ResourcesCreatorAddonsUpdateRequestFile {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("data");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PostV2ResourcesCreatorAddonsUpdateRequestFile
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV2ResourcesCreatorAddonsUpdateRequestFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV2ResourcesCreatorAddonsUpdateRequestFile is not found in the empty JSON string", PostV2ResourcesCreatorAddonsUpdateRequestFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV2ResourcesCreatorAddonsUpdateRequestFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV2ResourcesCreatorAddonsUpdateRequestFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostV2ResourcesCreatorAddonsUpdateRequestFile.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV2ResourcesCreatorAddonsUpdateRequestFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV2ResourcesCreatorAddonsUpdateRequestFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV2ResourcesCreatorAddonsUpdateRequestFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV2ResourcesCreatorAddonsUpdateRequestFile.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV2ResourcesCreatorAddonsUpdateRequestFile>() {
           @Override
           public void write(JsonWriter out, PostV2ResourcesCreatorAddonsUpdateRequestFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV2ResourcesCreatorAddonsUpdateRequestFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostV2ResourcesCreatorAddonsUpdateRequestFile given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostV2ResourcesCreatorAddonsUpdateRequestFile
  * @throws IOException if the JSON string is invalid with respect to PostV2ResourcesCreatorAddonsUpdateRequestFile
  */
  public static PostV2ResourcesCreatorAddonsUpdateRequestFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV2ResourcesCreatorAddonsUpdateRequestFile.class);
  }

 /**
  * Convert an instance of PostV2ResourcesCreatorAddonsUpdateRequestFile to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

