/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetOauth2Token200Response;
import org.openapitools.client.model.GetOauth2TokenRevoke200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oauth2Api
 */
@Disabled
public class Oauth2ApiTest {

    private final Oauth2Api api = new Oauth2Api();

    /**
     * Request an access token using an existing grant
     *
     * Supported grant types: authorization_code, refresh_token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOauth2TokenTest() throws ApiException {
        String authorization = null;
        String grantType = null;
        String code = null;
        String refreshToken = null;
        GetOauth2Token200Response response = api.getOauth2Token(authorization, grantType, code, refreshToken);
        // TODO: test validations
    }

    /**
     * Revoke an existing access or refresh token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOauth2TokenRevokeTest() throws ApiException {
        String authorization = null;
        String token = null;
        String tokenHint = null;
        GetOauth2TokenRevoke200Response response = api.getOauth2TokenRevoke(authorization, token, tokenHint);
        // TODO: test validations
    }

}
