/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PostV2ResourcesCreatorUpdate200Response;
import org.openapitools.client.model.PostV2ResourcesCreatorUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesCreatorApi
 */
@Disabled
public class ResourcesCreatorApiTest {

    private final ResourcesCreatorApi api = new ResourcesCreatorApi();

    /**
     * Post a resource update
     *
     * Creates a new version for the resource and optionally posts a public update message. The uploaded file must be encoded using base64 as part of the JSON request body shown below.    The request body (including the base64 encoded file data) cannot exceed 100MB. This roughly equates to a 67MB upload limit for the raw file when taking into account base64 encoding losses.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesCreatorUpdateTest() throws ApiException {
        PostV2ResourcesCreatorUpdateRequest postV2ResourcesCreatorUpdateRequest = null;
        PostV2ResourcesCreatorUpdate200Response response = api.postV2ResourcesCreatorUpdate(postV2ResourcesCreatorUpdateRequest);
        // TODO: test validations
    }

}
