/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetV2ResourcesCreatorBundles200Response;
import org.openapitools.client.model.GetV2ResourcesCreatorBundlesEntries200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesCreatorBundlesApi
 */
@Disabled
public class ResourcesCreatorBundlesApiTest {

    private final ResourcesCreatorBundlesApi api = new ResourcesCreatorBundlesApi();

    /**
     * Fetch a list of your bundles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV2ResourcesCreatorBundlesTest() throws ApiException {
        List bundleIds = null;
        GetV2ResourcesCreatorBundles200Response response = api.getV2ResourcesCreatorBundles(bundleIds);
        // TODO: test validations
    }

    /**
     * Fetch a list of your bundle entries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV2ResourcesCreatorBundlesEntriesTest() throws ApiException {
        List bundleIds = null;
        GetV2ResourcesCreatorBundlesEntries200Response response = api.getV2ResourcesCreatorBundlesEntries(bundleIds);
        // TODO: test validations
    }

}
