/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetV2ResourcesCreatorBatch200Response;
import org.openapitools.client.model.PostV2ResourcesCreatorBatch200Response;
import org.openapitools.client.model.PostV2ResourcesCreatorBatchRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesCreatorBatchApi
 */
@Disabled
public class ResourcesCreatorBatchApiTest {

    private final ResourcesCreatorBatchApi api = new ResourcesCreatorBatchApi();

    /**
     * Fetch a list of your batches edits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV2ResourcesCreatorBatchTest() throws ApiException {
        List batchIds = null;
        GetV2ResourcesCreatorBatch200Response response = api.getV2ResourcesCreatorBatch(batchIds);
        // TODO: test validations
    }

    /**
     * Submit a new batch edit
     *
     * Batch edits will be processed in the background meaning a successful call to this endpoint does not guarantee that the edits have been completed. You will instead receive an identifier to a batch edit which you can then use to fetch the status of via the below endpoint. This is not an atomic operation meaning some resources may be edited successfully and others may not be due to an error. You may only batch edit resources you own currently.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesCreatorBatchTest() throws ApiException {
        PostV2ResourcesCreatorBatchRequest postV2ResourcesCreatorBatchRequest = null;
        PostV2ResourcesCreatorBatch200Response response = api.postV2ResourcesCreatorBatch(postV2ResourcesCreatorBatchRequest);
        // TODO: test validations
    }

}
