/*
 * BuiltByBit API
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.GetResourcesDiscoverCategories200Response;
import org.openapitools.client.model.GetResourcesDiscoverResources200Response;
import org.openapitools.client.model.GetResourcesDiscoverResources4XXResponse;
import org.openapitools.client.model.GetV2ResourcesDiscoverCartView200Response;
import org.openapitools.client.model.GetV2ResourcesDiscoverLicenses200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartAdd2XXResponse;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartAddRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCheckout200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponAdd200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponAddRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponRemove200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartCouponRemoveRequest;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartRemove200Response;
import org.openapitools.client.model.PostV2ResourcesDiscoverCartRemoveRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesDiscoveryApi
 */
@Disabled
public class ResourcesDiscoveryApiTest {

    private final ResourcesDiscoveryApi api = new ResourcesDiscoveryApi();

    /**
     * Fetch a list of categories
     *
     * Supported &#39;with&#39; hints:  - Children: includes all subcategories and their children
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourcesDiscoverCategoriesTest() throws ApiException {
        String categoryId = null;
        String with = null;
        GetResourcesDiscoverCategories200Response response = api.getResourcesDiscoverCategories(categoryId, with);
        // TODO: test validations
    }

    /**
     * Fetch a list of resources
     *
     * Supported &#39;with&#39; hints:  - &#x60;filters&#x60;: include dynamic filter information in the response.  - See &#39;Resource&#39; model for additional &#39;with&#39; hints.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourcesDiscoverResourcesTest() throws ApiException {
        String categoryId = null;
        String with = null;
        Object filters = null;
        String resourceIds = null;
        Integer page = null;
        BigDecimal perPage = null;
        Boolean noDependencies = null;
        GetResourcesDiscoverResources200Response response = api.getResourcesDiscoverResources(categoryId, with, filters, resourceIds, page, perPage, noDependencies);
        // TODO: test validations
    }

    /**
     * View the user&#39;s cart items
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV2ResourcesDiscoverCartViewTest() throws ApiException {
        GetV2ResourcesDiscoverCartView200Response response = api.getV2ResourcesDiscoverCartView();
        // TODO: test validations
    }

    /**
     * Fetch a list of the user&#39;s licenses
     *
     * Supported &#39;with&#39; hints:  - Resource: the resource the license is for if content_type &#x3D; &#x60;resource&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV2ResourcesDiscoverLicensesTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        String with = null;
        GetV2ResourcesDiscoverLicenses200Response response = api.getV2ResourcesDiscoverLicenses(page, perPage, with);
        // TODO: test validations
    }

    /**
     * Add items to a user&#39;s cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesDiscoverCartAddTest() throws ApiException {
        PostV2ResourcesDiscoverCartAddRequest postV2ResourcesDiscoverCartAddRequest = null;
        PostV2ResourcesDiscoverCartAdd2XXResponse response = api.postV2ResourcesDiscoverCartAdd(postV2ResourcesDiscoverCartAddRequest);
        // TODO: test validations
    }

    /**
     * Initiate a checkout of a user&#39;s cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesDiscoverCartCheckoutTest() throws ApiException {
        Object body = null;
        PostV2ResourcesDiscoverCartCheckout200Response response = api.postV2ResourcesDiscoverCartCheckout(body);
        // TODO: test validations
    }

    /**
     * Add a coupon to the user&#39;s cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesDiscoverCartCouponAddTest() throws ApiException {
        PostV2ResourcesDiscoverCartCouponAddRequest postV2ResourcesDiscoverCartCouponAddRequest = null;
        PostV2ResourcesDiscoverCartCouponAdd200Response response = api.postV2ResourcesDiscoverCartCouponAdd(postV2ResourcesDiscoverCartCouponAddRequest);
        // TODO: test validations
    }

    /**
     * Remove a coupon from the user&#39;s cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesDiscoverCartCouponRemoveTest() throws ApiException {
        PostV2ResourcesDiscoverCartCouponRemoveRequest postV2ResourcesDiscoverCartCouponRemoveRequest = null;
        PostV2ResourcesDiscoverCartCouponRemove200Response response = api.postV2ResourcesDiscoverCartCouponRemove(postV2ResourcesDiscoverCartCouponRemoveRequest);
        // TODO: test validations
    }

    /**
     * Remove an item from the user&#39;s cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV2ResourcesDiscoverCartRemoveTest() throws ApiException {
        PostV2ResourcesDiscoverCartRemoveRequest postV2ResourcesDiscoverCartRemoveRequest = null;
        PostV2ResourcesDiscoverCartRemove200Response response = api.postV2ResourcesDiscoverCartRemove(postV2ResourcesDiscoverCartRemoveRequest);
        // TODO: test validations
    }

}
